/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.appchat;

import com.mycompany.controllers.FrmAppSocialMediaController;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author MateyR
 */
public class FrmAppSocialMedia extends javax.swing.JFrame {
    
    private FrmAppSocialMediaController FrmAppcontroller;
    
    
    
    /**
     * Creates new form FrmAppSocialMedia
     */
    public FrmAppSocialMedia() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        FrmAppcontroller = new FrmAppSocialMediaController(this);
        
    }

    public FrmAppSocialMediaController getFrmAppcontroller() {
        return FrmAppcontroller;
    }
    
    
    

    public JDesktopPane getDtkContent() {
        return dtkContent;
    }

    public JMenuItem getMniSignIn() {
        return mniSignIn;
    }

    public JMenuItem getMniSignUp() {
        return mniSignUp;
    }

   
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtkContent = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnStart = new javax.swing.JMenu();
        mniSignUp = new javax.swing.JMenuItem();
        mniSignIn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SocialMedia");

        javax.swing.GroupLayout dtkContentLayout = new javax.swing.GroupLayout(dtkContent);
        dtkContent.setLayout(dtkContentLayout);
        dtkContentLayout.setHorizontalGroup(
            dtkContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dtkContentLayout.setVerticalGroup(
            dtkContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        getContentPane().add(dtkContent, java.awt.BorderLayout.CENTER);

        mnStart.setText("Start");

        mniSignUp.setText("Sign Up");
        mnStart.add(mniSignUp);

        mniSignIn.setText("Sign In");
        mnStart.add(mniSignIn);

        jMenuBar1.add(mnStart);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(414, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAppSocialMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAppSocialMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAppSocialMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAppSocialMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAppSocialMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtkContent;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnStart;
    private javax.swing.JMenuItem mniSignIn;
    private javax.swing.JMenuItem mniSignUp;
    // End of variables declaration//GEN-END:variables
}
